# Generated by Django 4.2 on 2026-04-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_expiry_minutes', models.PositiveIntegerField(default=5, help_text='OTP expiry time in minutes')),
                ('max_otp_attempts', models.PositiveIntegerField(default=3, help_text='Maximum OTP attempts allowed')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable system notifications')),
                ('auto_cleanup_days', models.PositiveIntegerField(default=30, help_text='Auto cleanup old records after days')),
                ('items_per_page', models.PositiveIntegerField(default=10, help_text='Number of items per page in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
    ]
