# Generated by Django 4.2 on 2026-03-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AlterModelOptions(
            name='securityguard',
            options={'verbose_name': 'Security Guard', 'verbose_name_plural': 'Security Guards'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securityguard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
