# Generated by Django 4.2 on 2026-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('security', 'Security'), ('guard', 'Security Guard')], default='resident', max_length=20),
        ),
    ]
