# Generated by Django 4.2 on 2026-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityguard',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Guard profile photo for identification', null=True, upload_to='guard_photos/'),
        ),
    ]
