# Generated by Django 4.2 on 2026-04-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_guard_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resident_photos/'),
        ),
    ]
