# Generated by Django 4.2 on 2026-03-27 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('visitor_register', 'Visitor Registration'), ('visitor_approve', 'Visitor Approval'), ('visitor_reject', 'Visitor Rejection'), ('otp_generate', 'OTP Generated'), ('otp_verify', 'OTP Verified'), ('gate_pass_issue', 'Gate Pass Issued'), ('gate_pass_cancel', 'Gate Pass Cancelled'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('system_error', 'System Error'), ('security_breach', 'Security Breach')], max_length=50)),
                ('description', models.TextField()),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning'), ('info', 'Info')], default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
            ],
            options={
                'verbose_name_plural': 'Admin Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='systemaudit',
            index=models.Index(fields=['user', 'action_type', 'timestamp'], name='audit_syste_user_id_9b170f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaudit',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_syste_target__4cf125_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaudit',
            index=models.Index(fields=['timestamp'], name='audit_syste_timesta_d35717_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaudit',
            index=models.Index(fields=['action_type'], name='audit_syste_action__e0b2e4_idx'),
        ),
    ]
