# Generated by Django 4.2 on 2026-03-27 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemaudit',
            name='action_type',
            field=models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_create', 'User Creation'), ('user_update', 'User Update'), ('user_delete', 'User Deletion'), ('visitor_register', 'Visitor Registration'), ('visitor_approve', 'Visitor Approval'), ('visitor_reject', 'Visitor Rejection'), ('visitor_exit', 'Visitor Exit'), ('otp_generate', 'OTP Generation'), ('otp_verify', 'OTP Verification'), ('gate_pass_issue', 'Gate Pass Issued'), ('gate_pass_revoke', 'Gate Pass Revoked'), ('system_error', 'System Error'), ('security_breach', 'Security Breach'), ('data_export', 'Data Export'), ('config_change', 'Configuration Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning'), ('info', 'Information')], default='success', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='target_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='systemaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
