# Generated by Django 4.2 on 2026-03-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_systemaudit_action_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemaudit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Audit', 'verbose_name_plural': 'System Audits'},
        ),
    ]
