# Generated by Django 4.2 on 2026-03-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_systemaudit_options_delete_adminactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminActivity',
        ),
    ]
