# Generated by Django 4.2 on 2026-03-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_delete_adminactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemaudit',
            name='session_key',
        ),
    ]
