# Generated by Django 4.2 on 2026-03-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('identity_proof', models.CharField(choices=[('aadhar', 'Aadhar'), ('passport', 'Passport'), ('license', 'Driving License'), ('others', 'Others')], default='aadhar', max_length=50)),
                ('identity_number', models.CharField(blank=True, max_length=50, null=True)),
                ('visitor_photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='accounts.resident')),
                ('security_guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.securityguard')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resident')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resident')),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(max_length=20, unique=True)),
                ('issue_time', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resident')),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitor')),
            ],
        ),
    ]
