# Generated by Django 4.2 on 2026-03-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_admin_options_alter_resident_options_and_more'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gatepass',
            options={'ordering': ['-issue_time'], 'verbose_name': 'Gate Pass', 'verbose_name_plural': 'Gate Passes'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
        migrations.AlterModelOptions(
            name='visitorhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visitor History', 'verbose_name_plural': 'Visitor Histories'},
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_gate_passes', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_otps', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='security_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitors', to='accounts.securityguard'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_history', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_history', to='visitors.visitor'),
        ),
    ]
