# Generated by Django 4.2 on 2026-03-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_user_alter_resident_user_and_more'),
        ('visitors', '0002_alter_gatepass_options_alter_otp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='security_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='accounts.securityguard'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorhistories', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorhistory', to='visitors.visitor'),
        ),
    ]
