# Generated by Django 4.2 on 2026-03-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_user_type'),
        ('visitors', '0003_alter_gatepass_resident_alter_gatepass_visitor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='security_guard',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='security_guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gatepasses', to='accounts.securityguard'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepasses', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_histories', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_histories', to='visitors.visitor'),
        ),
    ]
