# Generated by Django 4.2 on 2026-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_visitor_entry_time_remove_visitor_exit_time_and_more'),
    ]

    operations = [
        # Add missing fields to match project requirements
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(
                'accounts.resident', 
                on_delete=models.CASCADE, 
                related_name='visitors',
                null=True, 
                blank=True
            ),
        ),
    ]
