# Generated by Django 4.2 on 2026-03-27 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_user_type'),
        ('visitors', '0005_auto_20260327_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='security_guard',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='visitorhistory',
            name='resident',
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='visitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose',
            field=models.CharField(default='delivery', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='accounts.resident'),
        ),
        migrations.AlterField(
            model_name='visitorhistory',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorhistory', to='visitors.visitor'),
        ),
    ]
