# Generated by Django 4.2 on 2026-03-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_remove_gatepass_resident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
