# Generated by Django 4.2 on 2026-04-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_resident_user_alter_securityguard_user'),
        ('visitors', '0008_alter_visitorhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to='accounts.securityguard'),
        ),
    ]
